language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
before_script:
  - pip install codecov
script:
  - coverage run setup.py test
after_success:
  - codecov
notifications:
  email:
    - anindya@anindyaspaul.com
